# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_service_pb2 as audio__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audio_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioInferenceServiceStub(object):
    """Audio inference service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeAudio = channel.unary_unary(
                '/audio_inference.AudioInferenceService/RecognizeAudio',
                request_serializer=audio__service__pb2.AudioRequest.SerializeToString,
                response_deserializer=audio__service__pb2.AudioResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/audio_inference.AudioInferenceService/HealthCheck',
                request_serializer=audio__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=audio__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class AudioInferenceServiceServicer(object):
    """Audio inference service."""

    def RecognizeAudio(self, request, context):
        """Audio inference method."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check method."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeAudio,
                    request_deserializer=audio__service__pb2.AudioRequest.FromString,
                    response_serializer=audio__service__pb2.AudioResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=audio__service__pb2.HealthRequest.FromString,
                    response_serializer=audio__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_inference.AudioInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audio_inference.AudioInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioInferenceService(object):
    """Audio inference service."""

    @staticmethod
    def RecognizeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio_inference.AudioInferenceService/RecognizeAudio',
            audio__service__pb2.AudioRequest.SerializeToString,
            audio__service__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio_inference.AudioInferenceService/HealthCheck',
            audio__service__pb2.HealthRequest.SerializeToString,
            audio__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
