# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'audio_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61udio_service.proto\x12\x0f\x61udio_inference\"\xbf\x01\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x18\n\x10\x61udio_data_shape\x18\x02 \x03(\x05\x12\x12\n\naudio_path\x18\x03 \x01(\t\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x0c\n\x04task\x18\x05 \x01(\t\x12\x0c\n\x04lang\x18\x06 \x01(\t\x12\x0f\n\x07speaker\x18\x07 \x01(\t\x12\x0c\n\x04text\x18\x08 \x01(\t\x12\x0b\n\x03key\x18\t \x01(\t\x12\x10\n\x08\x64uration\x18\n \x01(\x02\"\xd6\x01\n\rAudioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x13\n\x0bresult_text\x18\x03 \x01(\t\x12\x16\n\x0einference_time\x18\x04 \x01(\x02\x12\x12\n\naudio_path\x18\x05 \x01(\t\x12\x0b\n\x03key\x18\x06 \x01(\t\x12\x0c\n\x04task\x18\x07 \x01(\t\x12\x0c\n\x04lang\x18\x08 \x01(\t\x12\x0f\n\x07speaker\x18\t \x01(\t\x12\x0e\n\x06prompt\x18\n \x01(\t\x12\x12\n\ntotal_time\x18\x0b \x01(\x02\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb8\x01\n\x15\x41udioInferenceService\x12O\n\x0eRecognizeAudio\x12\x1d.audio_inference.AudioRequest\x1a\x1e.audio_inference.AudioResponse\x12N\n\x0bHealthCheck\x12\x1e.audio_inference.HealthRequest\x1a\x1f.audio_inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=41
  _globals['_AUDIOREQUEST']._serialized_end=232
  _globals['_AUDIORESPONSE']._serialized_start=235
  _globals['_AUDIORESPONSE']._serialized_end=449
  _globals['_HEALTHREQUEST']._serialized_start=451
  _globals['_HEALTHREQUEST']._serialized_end=466
  _globals['_HEALTHRESPONSE']._serialized_start=468
  _globals['_HEALTHRESPONSE']._serialized_end=517
  _globals['_AUDIOINFERENCESERVICE']._serialized_start=520
  _globals['_AUDIOINFERENCESERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
